"""Number definitions for EcoFlow Delta Pro."""

from __future__ import annotations

from homeassistant.components.number import NumberMode

from ..base import EcoFlowNumberDef

NUMBERS: list[EcoFlowNumberDef] = [
    EcoFlowNumberDef(
        key="max_charge_level",
        name="Max Charge Level",
        state_key="ems.maxChargeSoc",
        param_key="maxChgSoc",
        command_params={"cmd_set": 32, "cmd_id": 49},
        min_value=50,
        max_value=100,
        step=1,
        unit="%",
        icon="mdi:battery-charging-100",
    ),
    EcoFlowNumberDef(
        key="min_discharge_level",
        name="Min Discharge Level",
        state_key="ems.minDsgSoc",
        param_key="minDsgSoc",
        command_params={"cmd_set": 32, "cmd_id": 51},
        min_value=0,
        max_value=30,
        step=1,
        unit="%",
        icon="mdi:battery-10",
    ),
    EcoFlowNumberDef(
        key="car_input_current",
        name="Car Input Current",
        state_key="mppt.cfgDcChgCurrent",
        param_key="currMa",
        command_params={"cmd_set": 32, "cmd_id": 71},
        min_value=4000,
        max_value=8000,
        step=1000,
        unit="mA",
        icon="mdi:car-battery",
    ),
    EcoFlowNumberDef(
        key="screen_brightness",
        name="Screen Brightness",
        state_key="pd.lcdBrightness",
        param_key="lcdBrightness",
        command_params={"cmd_set": 32, "cmd_id": 39},
        min_value=0,
        max_value=100,
        step=10,
        unit="%",
        icon="mdi:brightness-6",
    ),
    EcoFlowNumberDef(
        key="device_standby_time",
        name="Device Standby Time",
        state_key="pd.standByMode",
        param_key="standByMode",
        command_params={"cmd_set": 32, "cmd_id": 33},
        min_value=0,
        max_value=5999,
        step=30,
        unit="min",
        icon="mdi:timer-sleep",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="screen_timeout",
        name="Screen Timeout",
        state_key="pd.lcdOffSec",
        param_key="lcdTime",
        command_params={"cmd_set": 32, "cmd_id": 39},
        min_value=0,
        max_value=1800,
        step=30,
        unit="s",
        icon="mdi:monitor-off",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="ac_standby_time",
        name="AC Standby Time",
        state_key="inv.cfgStandbyMin",
        param_key="standByMins",
        command_params={"cmd_set": 32, "cmd_id": 153},
        min_value=0,
        max_value=720,
        step=30,
        unit="min",
        icon="mdi:timer",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="ac_charging_power",
        name="AC Charging Power",
        state_key="inv.cfgSlowChgWatts",
        param_key="slowChgPower",
        command_params={"cmd_set": 32, "cmd_id": 69},
        min_value=200,
        max_value=2900,
        step=100,
        unit="W",
        icon="mdi:lightning-bolt",
    ),
    EcoFlowNumberDef(
        key="generator_auto_start_soc",
        name="Generator Auto Start SOC",
        state_key="ems.minOpenOilEbSoc",
        param_key="openOilSoc",
        command_params={"cmd_set": 32, "cmd_id": 52},
        min_value=0,
        max_value=100,
        step=5,
        unit="%",
        icon="mdi:engine",
    ),
    EcoFlowNumberDef(
        key="generator_auto_stop_soc",
        name="Generator Auto Stop SOC",
        state_key="ems.maxCloseOilEbSoc",
        param_key="closeOilSoc",
        command_params={"cmd_set": 32, "cmd_id": 53},
        min_value=0,
        max_value=100,
        step=5,
        unit="%",
        icon="mdi:engine-off",
    ),
]
