"""Sensor definitions for EcoFlow Delta Pro."""

from __future__ import annotations

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfTime,
)

from ..base import EcoFlowSensorDef

SENSORS: list[EcoFlowSensorDef] = [
    # ========================================================================
    # BMS Master - Battery Management System
    # ========================================================================
    EcoFlowSensorDef(
        key="bms_soc",
        name="Battery Level",
        state_key="bmsMaster.soc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_temp",
        name="Battery Temperature",
        state_key="bmsMaster.temp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_input_watts",
        name="Battery Input Power",
        state_key="bmsMaster.inputWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="bms_output_watts",
        name="Battery Output Power",
        state_key="bmsMaster.outputWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-arrow-down",
    ),
    EcoFlowSensorDef(
        key="bms_vol",
        name="Battery Voltage",
        state_key="bmsMaster.vol",
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_amp",
        name="Battery Current",
        state_key="bmsMaster.amp",
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_soh",
        name="Battery Health",
        state_key="bmsMaster.soh",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart",
    ),
    EcoFlowSensorDef(
        key="bms_design_cap",
        name="Design Capacity",
        state_key="bmsMaster.designCap",
        unit="mAh",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-high",
    ),
    EcoFlowSensorDef(
        key="bms_remain_cap",
        name="Remaining Capacity",
        state_key="bmsMaster.remainCap",
        unit="mAh",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery",
    ),
    EcoFlowSensorDef(
        key="bms_full_cap",
        name="Full Capacity",
        state_key="bmsMaster.fullCap",
        unit="mAh",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-high",
    ),
    EcoFlowSensorDef(
        key="bms_max_cell_temp",
        name="Max Cell Temperature",
        state_key="bmsMaster.maxCellTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-high",
    ),
    EcoFlowSensorDef(
        key="bms_min_cell_temp",
        name="Min Cell Temperature",
        state_key="bmsMaster.minCellTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-low",
    ),
    EcoFlowSensorDef(
        key="bms_remain_time",
        name="Battery Remaining Time",
        state_key="bmsMaster.remainTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="bms_err_code",
        name="BMS Error Code",
        state_key="bmsMaster.errCode",
        icon="mdi:alert-circle",
    ),
    # ========================================================================
    # Inverter
    # ========================================================================
    EcoFlowSensorDef(
        key="inv_input_watts",
        name="Inverter Input Power",
        state_key="inv.inputWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:power-plug",
    ),
    EcoFlowSensorDef(
        key="inv_output_watts",
        name="Inverter Output Power",
        state_key="inv.outputWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:power-socket",
    ),
    EcoFlowSensorDef(
        key="inv_out_freq",
        name="AC Output Frequency",
        state_key="inv.invOutFreq",
        unit=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:sine-wave",
    ),
    EcoFlowSensorDef(
        key="inv_ac_in_freq",
        name="AC Input Frequency",
        state_key="inv.acInFreq",
        unit=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:sine-wave",
    ),
    EcoFlowSensorDef(
        key="inv_out_temp",
        name="Inverter Temperature",
        state_key="inv.outTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_dc_in_temp",
        name="DC Input Temperature",
        state_key="inv.dcInTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_cfg_slow_chg_watts",
        name="AC Slow Charging Power",
        state_key="inv.cfgSlowChgWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:lightning-bolt",
    ),
    EcoFlowSensorDef(
        key="inv_cfg_standby_min",
        name="AC Standby Time",
        state_key="inv.cfgStandbyMin",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="inv_err_code",
        name="Inverter Error Code",
        state_key="inv.errCode",
        icon="mdi:alert-circle",
    ),
    # ========================================================================
    # MPPT - Solar Charger
    # ========================================================================
    EcoFlowSensorDef(
        key="mppt_in_watts",
        name="Solar Input Power",
        state_key="mppt.inWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="mppt_out_watts",
        name="MPPT Output Power",
        state_key="mppt.outWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    EcoFlowSensorDef(
        key="mppt_temp",
        name="MPPT Temperature",
        state_key="mppt.mpptTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="mppt_dc12v_watts",
        name="DC 12V Output Power",
        state_key="mppt.dcdc12vWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-battery",
    ),
    EcoFlowSensorDef(
        key="mppt_car_out_watts",
        name="Car Charger Output Power",
        state_key="mppt.carOutWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car",
    ),
    EcoFlowSensorDef(
        key="mppt_car_temp",
        name="Car Charger Temperature",
        state_key="mppt.carTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="mppt_fault_code",
        name="MPPT Fault Code",
        state_key="mppt.faultCode",
        icon="mdi:alert-circle",
    ),
    # ========================================================================
    # PD - Power Distribution
    # ========================================================================
    EcoFlowSensorDef(
        key="pd_soc",
        name="Display SOC",
        state_key="pd.soc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="pd_watts_out_sum",
        name="Total Output Power",
        state_key="pd.wattsOutSum",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:transmission-tower-export",
    ),
    EcoFlowSensorDef(
        key="pd_watts_in_sum",
        name="Total Input Power",
        state_key="pd.wattsInSum",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:transmission-tower-import",
    ),
    EcoFlowSensorDef(
        key="pd_remain_time",
        name="Remaining Time",
        state_key="pd.remainTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="pd_usb1_watts",
        name="USB 1 Output Power",
        state_key="pd.usb1Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-port",
    ),
    EcoFlowSensorDef(
        key="pd_usb2_watts",
        name="USB 2 Output Power",
        state_key="pd.usb2Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-port",
    ),
    EcoFlowSensorDef(
        key="pd_qc_usb1_watts",
        name="QC USB 1 Output Power",
        state_key="pd.qcUsb1Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-port",
    ),
    EcoFlowSensorDef(
        key="pd_qc_usb2_watts",
        name="QC USB 2 Output Power",
        state_key="pd.qcUsb2Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-port",
    ),
    EcoFlowSensorDef(
        key="pd_typec1_watts",
        name="Type-C 1 Output Power",
        state_key="pd.typec1Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-c-port",
    ),
    EcoFlowSensorDef(
        key="pd_typec2_watts",
        name="Type-C 2 Output Power",
        state_key="pd.typec2Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-c-port",
    ),
    EcoFlowSensorDef(
        key="pd_car_watts",
        name="Car Output Power",
        state_key="pd.carWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car",
    ),
    EcoFlowSensorDef(
        key="pd_standby_mode",
        name="Device Standby Time",
        state_key="pd.standByMode",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer-sleep",
    ),
    EcoFlowSensorDef(
        key="pd_lcd_off_sec",
        name="Screen Off Time",
        state_key="pd.lcdOffSec",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:monitor-off",
    ),
    EcoFlowSensorDef(
        key="pd_lcd_brightness",
        name="Screen Brightness",
        state_key="pd.lcdBrightness",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:brightness-6",
    ),
    EcoFlowSensorDef(
        key="pd_chg_power_dc",
        name="Cumulative DC Charged",
        state_key="pd.chgPowerDc",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="pd_chg_sun_power",
        name="Cumulative Solar Charged",
        state_key="pd.chgSunPower",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="pd_chg_power_ac",
        name="Cumulative AC Charged",
        state_key="pd.chgPowerAc",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:power-plug",
    ),
    EcoFlowSensorDef(
        key="pd_dsg_power_dc",
        name="Cumulative DC Discharged",
        state_key="pd.dsgPowerDc",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-arrow-down",
    ),
    EcoFlowSensorDef(
        key="pd_dsg_power_ac",
        name="Cumulative AC Discharged",
        state_key="pd.dsgPowerAc",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:power-socket",
    ),
    EcoFlowSensorDef(
        key="pd_err_code",
        name="PD Error Code",
        state_key="pd.errCode",
        icon="mdi:alert-circle",
    ),
    EcoFlowSensorDef(
        key="pd_wifi_rssi",
        name="WiFi Signal Strength",
        state_key="pd.wifiRssi",
        unit="dBm",
        device_class=SensorDeviceClass.SIGNAL_STRENGTH,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:wifi",
    ),
    # ========================================================================
    # EMS - Energy Management System
    # ========================================================================
    EcoFlowSensorDef(
        key="ems_max_charge_soc",
        name="Max Charge Level",
        state_key="ems.maxChargeSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging-100",
    ),
    EcoFlowSensorDef(
        key="ems_min_dsg_soc",
        name="Min Discharge Level",
        state_key="ems.minDsgSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-10",
    ),
    EcoFlowSensorDef(
        key="ems_min_open_oil_soc",
        name="Generator Auto Start SOC",
        state_key="ems.minOpenOilEbSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:engine",
    ),
    EcoFlowSensorDef(
        key="ems_max_close_oil_soc",
        name="Generator Auto Stop SOC",
        state_key="ems.maxCloseOilEbSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:engine-off",
    ),
    EcoFlowSensorDef(
        key="ems_chg_remain_time",
        name="Charge Remaining Time",
        state_key="ems.chgRemainTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="ems_dsg_remain_time",
        name="Discharge Remaining Time",
        state_key="ems.dsgRemainTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-arrow-down",
    ),
    EcoFlowSensorDef(
        key="ems_lcd_show_soc",
        name="LCD Display SOC",
        state_key="ems.lcdShowSoc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
]
