"""Delta 2 binary sensor definitions."""

from __future__ import annotations

from homeassistant.components.binary_sensor import BinarySensorDeviceClass

from ..base import EcoFlowBinarySensorDef

BINARY_SENSORS = [
    EcoFlowBinarySensorDef(
        key="ac_in_connected",
        name="AC Input Connected",
        state_key="acInConnected",
        device_class=BinarySensorDeviceClass.PLUG,
        icon_on="mdi:power-plug",
        icon_off="mdi:power-plug-off",
        derived=True,
        derive_from="inv.inputWatts",
        derive_condition=lambda v: v is not None and v > 0,
    ),
    EcoFlowBinarySensorDef(
        key="solar_connected",
        name="Solar Input Connected",
        state_key="solarConnected",
        device_class=BinarySensorDeviceClass.PLUG,
        icon_on="mdi:solar-power",
        icon_off="mdi:solar-power-variant-outline",
        derived=True,
        derive_from="mppt.inWatts",
        derive_condition=lambda v: v is not None and v > 0,
    ),
    EcoFlowBinarySensorDef(
        key="is_charging",
        name="Charging",
        state_key="isCharging",
        device_class=BinarySensorDeviceClass.BATTERY_CHARGING,
        icon_on="mdi:battery-charging",
        icon_off="mdi:battery",
        derived=True,
        derive_from="pd.wattsInSum",
        derive_condition=lambda v: v is not None and v > 10,
    ),
    EcoFlowBinarySensorDef(
        key="is_discharging",
        name="Discharging",
        state_key="isDischarging",
        device_class=BinarySensorDeviceClass.POWER,
        icon_on="mdi:battery-arrow-down",
        icon_off="mdi:battery",
        derived=True,
        derive_from="pd.wattsOutSum",
        derive_condition=lambda v: v is not None and v > 10,
    ),
    EcoFlowBinarySensorDef(
        key="ac_out_enabled",
        name="AC Output Enabled",
        state_key="mppt.cfgAcEnabled",
        device_class=BinarySensorDeviceClass.POWER,
        icon_on="mdi:power-socket",
        icon_off="mdi:power-socket-off",
    ),
    EcoFlowBinarySensorDef(
        key="dc_out_enabled",
        name="DC Output Enabled",
        state_key="pd.dcOutState",
        device_class=BinarySensorDeviceClass.POWER,
        icon_on="mdi:current-dc",
        icon_off="mdi:current-dc",
    ),
    EcoFlowBinarySensorDef(
        key="car_charger_enabled",
        name="Car Charger Enabled",
        state_key="mppt.carState",
        device_class=BinarySensorDeviceClass.POWER,
        icon_on="mdi:car",
        icon_off="mdi:car-off",
    ),
    EcoFlowBinarySensorDef(
        key="battery_low",
        name="Battery Low",
        state_key="batteryLow",
        device_class=BinarySensorDeviceClass.BATTERY,
        icon_on="mdi:battery-alert",
        icon_off="mdi:battery",
        derived=True,
        derive_from="bms_bmsStatus.soc",
        derive_condition=lambda v: v is not None and v < 20,
    ),
    EcoFlowBinarySensorDef(
        key="battery_full",
        name="Battery Full",
        state_key="batteryFull",
        device_class=BinarySensorDeviceClass.BATTERY,
        icon_on="mdi:battery-check",
        icon_off="mdi:battery",
        derived=True,
        derive_from="bms_bmsStatus.soc",
        derive_condition=lambda v: v is not None and v >= 100,
    ),
    EcoFlowBinarySensorDef(
        key="x_boost_enabled",
        name="X-Boost Enabled",
        state_key="mppt.cfgAcXboost",
        icon_on="mdi:lightning-bolt",
        icon_off="mdi:lightning-bolt-outline",
    ),
    EcoFlowBinarySensorDef(
        key="beeper_silent",
        name="Beeper Silent Mode",
        state_key="mppt.beepState",
        icon_on="mdi:volume-off",
        icon_off="mdi:volume-high",
    ),
    EcoFlowBinarySensorDef(
        key="over_temp",
        name="Over Temperature",
        state_key="overTemp",
        device_class=BinarySensorDeviceClass.HEAT,
        icon_on="mdi:thermometer-alert",
        icon_off="mdi:thermometer",
        derived=True,
        derive_from="bms_bmsStatus.temp",
        derive_condition=lambda v: v is not None and v > 45,
    ),
]
