"""Delta 2 number definitions."""

from __future__ import annotations

from homeassistant.components.number import NumberMode

from ..base import EcoFlowNumberDef

NUMBERS = [
    EcoFlowNumberDef(
        key="max_charge_level",
        name="Max Charge Level",
        state_key="bms_emsStatus.maxChargeSoc",
        param_key="maxChgSoc",
        command_params={"module_type": 2, "operate_type": "upsConfig"},
        min_value=50,
        max_value=100,
        step=1,
        unit="%",
        icon="mdi:battery-charging-100",
    ),
    EcoFlowNumberDef(
        key="min_discharge_level",
        name="Min Discharge Level",
        state_key="bms_emsStatus.minDsgSoc",
        param_key="minDsgSoc",
        command_params={"module_type": 2, "operate_type": "dsgCfg"},
        min_value=0,
        max_value=30,
        step=1,
        unit="%",
        icon="mdi:battery-10",
    ),
    EcoFlowNumberDef(
        key="ac_charging_power",
        name="AC Charging Power",
        state_key="mppt.cfgChgWatts",
        param_key="chgWatts",
        command_params={"module_type": 5, "operate_type": "acChgCfg"},
        min_value=100,
        max_value=1200,
        step=100,
        unit="W",
        icon="mdi:lightning-bolt",
    ),
    EcoFlowNumberDef(
        key="device_standby_time",
        name="Device Standby Time",
        state_key="pd.standbyMin",
        param_key="standbyMin",
        command_params={"module_type": 1, "operate_type": "standbyTime"},
        min_value=0,
        max_value=720,
        step=30,
        unit="min",
        icon="mdi:timer-sleep",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="screen_timeout",
        name="Screen Timeout",
        state_key="pd.lcdOffSec",
        param_key="delayOff",
        command_params={"module_type": 1, "operate_type": "lcdCfg"},
        min_value=0,
        max_value=1800,
        step=30,
        unit="s",
        icon="mdi:monitor-off",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="screen_brightness",
        name="Screen Brightness",
        state_key="pd.brightLevel",
        param_key="brighLevel",
        command_params={"module_type": 1, "operate_type": "lcdCfg"},
        min_value=0,
        max_value=3,
        step=1,
        icon="mdi:brightness-6",
    ),
    EcoFlowNumberDef(
        key="dc_charging_current",
        name="DC Charging Current",
        state_key="mppt.dcChgCurrent",
        param_key="dcChgCfg",
        command_params={"module_type": 5, "operate_type": "dcChgCfg"},
        min_value=4000,
        max_value=10000,
        step=1000,
        unit="mA",
        icon="mdi:current-dc",
    ),
    EcoFlowNumberDef(
        key="ac_standby_time",
        name="AC Standby Time",
        state_key="mppt.acStandbyMins",
        param_key="standbyMins",
        command_params={"module_type": 5, "operate_type": "standbyTime"},
        min_value=0,
        max_value=720,
        step=30,
        unit="min",
        icon="mdi:timer",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="car_standby_time",
        name="Car Charger Standby Time",
        state_key="mppt.carStandbyMin",
        param_key="standbyMins",
        command_params={"module_type": 5, "operate_type": "carStandby"},
        min_value=0,
        max_value=720,
        step=30,
        unit="min",
        icon="mdi:car-clock",
        mode=NumberMode.BOX,
    ),
]
