"""Delta 2 sensor definitions."""

from __future__ import annotations

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfTime,
)

from ..base import EcoFlowSensorDef

SENSORS = [
    # ========================================================================
    # Battery / BMS Sensors
    # ========================================================================
    EcoFlowSensorDef(
        key="bms_soc",
        name="Battery Level",
        state_key="bms_bmsStatus.soc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_soc_float",
        name="Battery Level (Precise)",
        state_key="bms_bmsStatus.f32ShowSoc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_voltage",
        name="Battery Voltage",
        state_key="bms_bmsStatus.vol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_current",
        name="Battery Current",
        state_key="bms_bmsStatus.amp",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_temp",
        name="Battery Temperature",
        state_key="bms_bmsStatus.temp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_cycles",
        name="Battery Cycles",
        state_key="bms_bmsStatus.cycles",
        unit="cycles",
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:sync",
    ),
    EcoFlowSensorDef(
        key="bms_design_cap",
        name="Design Capacity",
        state_key="bms_bmsStatus.designCap",
        unit="mAh",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-high",
    ),
    EcoFlowSensorDef(
        key="bms_full_cap",
        name="Full Capacity",
        state_key="bms_bmsStatus.fullCap",
        unit="mAh",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-high",
    ),
    EcoFlowSensorDef(
        key="bms_remain_cap",
        name="Remaining Capacity",
        state_key="bms_bmsStatus.remainCap",
        unit="mAh",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery",
    ),
    EcoFlowSensorDef(
        key="bms_soh",
        name="Battery Health",
        state_key="bms_bmsStatus.soh",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart",
    ),
    EcoFlowSensorDef(
        key="bms_max_cell_vol",
        name="Max Cell Voltage",
        state_key="bms_bmsStatus.maxCellVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_min_cell_vol",
        name="Min Cell Voltage",
        state_key="bms_bmsStatus.minCellVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_max_cell_temp",
        name="Max Cell Temperature",
        state_key="bms_bmsStatus.maxCellTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-high",
    ),
    EcoFlowSensorDef(
        key="bms_min_cell_temp",
        name="Min Cell Temperature",
        state_key="bms_bmsStatus.minCellTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-low",
    ),
    EcoFlowSensorDef(
        key="bms_err_code",
        name="BMS Error Code",
        state_key="bms_bmsStatus.errCode",
        icon="mdi:alert-circle",
    ),
    # ========================================================================
    # Battery Power & State (Extended)
    # ========================================================================
    EcoFlowSensorDef(
        key="bms_input_watts",
        name="Battery Input Power",
        state_key="bms_bmsStatus.inputWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="bms_output_watts",
        name="Battery Output Power",
        state_key="bms_bmsStatus.outputWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-arrow-down",
    ),
    EcoFlowSensorDef(
        key="bms_remain_time",
        name="Battery Remaining Time",
        state_key="bms_bmsStatus.remainTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="bms_chg_state",
        name="Battery Charge State",
        state_key="bms_bmsStatus.chgState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-sync",
        options=["not_charging", "charging"],
    ),
    EcoFlowSensorDef(
        key="bms_target_soc",
        name="Battery Target SOC",
        state_key="bms_bmsStatus.targetSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging-100",
    ),
    EcoFlowSensorDef(
        key="bms_act_soc",
        name="Battery Actual SOC",
        state_key="bms_bmsStatus.actSoc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_balance_state",
        name="Cell Balancing State",
        state_key="bms_bmsStatus.balanceState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:scale-balance",
        options=["not_balancing", "balancing"],
    ),
    EcoFlowSensorDef(
        key="bms_min_mos_temp",
        name="Min MOS Temperature",
        state_key="bms_bmsStatus.minMosTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-low",
    ),
    EcoFlowSensorDef(
        key="bms_max_mos_temp",
        name="Max MOS Temperature",
        state_key="bms_bmsStatus.maxMosTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-high",
    ),
    EcoFlowSensorDef(
        key="bms_real_soh",
        name="Battery Real Health",
        state_key="bms_bmsStatus.realSoh",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart",
    ),
    EcoFlowSensorDef(
        key="bms_cyc_soh",
        name="Battery Cycle Health",
        state_key="bms_bmsStatus.cycSoh",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart-variant",
    ),
    EcoFlowSensorDef(
        key="bms_mos_state",
        name="MOS State",
        state_key="bms_bmsStatus.mosState",
        icon="mdi:electric-switch",
    ),
    EcoFlowSensorDef(
        key="bms_fault",
        name="BMS Fault",
        state_key="bms_bmsStatus.bmsFault",
        icon="mdi:alert-circle",
    ),
    EcoFlowSensorDef(
        key="bms_all_fault",
        name="BMS All Faults",
        state_key="bms_bmsStatus.allBmsFault",
        icon="mdi:alert-circle-outline",
    ),
    EcoFlowSensorDef(
        key="bms_all_err_code",
        name="BMS All Error Codes",
        state_key="bms_bmsStatus.allErrCode",
        icon="mdi:alert",
    ),
    # ========================================================================
    # Battery Info (Extended)
    # ========================================================================
    EcoFlowSensorDef(
        key="bms_info_accu_chg_energy",
        name="Total Charge Energy",
        state_key="bms_bmsInfo.accuChgEnergy",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="bms_info_accu_dsg_energy",
        name="Total Discharge Energy",
        state_key="bms_bmsInfo.accuDsgEnergy",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-arrow-down",
    ),
    EcoFlowSensorDef(
        key="bms_info_accu_chg_cap",
        name="Total Charge Capacity",
        state_key="bms_bmsInfo.accuChgCap",
        unit="mAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-plus",
    ),
    EcoFlowSensorDef(
        key="bms_info_accu_dsg_cap",
        name="Total Discharge Capacity",
        state_key="bms_bmsInfo.accuDsgCap",
        unit="mAh",
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:battery-minus",
    ),
    EcoFlowSensorDef(
        key="bms_info_round_trip",
        name="Round Trip Efficiency",
        state_key="bms_bmsInfo.roundTrip",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:percent",
    ),
    EcoFlowSensorDef(
        key="bms_info_power_capability",
        name="Power Capability",
        state_key="bms_bmsInfo.powerCapability",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    EcoFlowSensorDef(
        key="bms_info_deep_dsg_cnt",
        name="Deep Discharge Count",
        state_key="bms_bmsInfo.deepDsgCnt",
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:counter",
    ),
    EcoFlowSensorDef(
        key="bms_info_self_dsg_rate",
        name="Self Discharge Rate",
        state_key="bms_bmsInfo.selfDsgRate",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-arrow-down-outline",
    ),
    EcoFlowSensorDef(
        key="bms_info_soh",
        name="Battery Info SOH",
        state_key="bms_bmsInfo.soh",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart",
    ),
    # ========================================================================
    # Extra Battery 1 (bms_kitInfo.watts[0])
    # Note: These sensors use kit_index/kit_field for array element access.
    # ========================================================================
    EcoFlowSensorDef(
        key="extra_bat1_connected",
        name="Extra Battery 1 Connected",
        state_key="bms_kitInfo.watts",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-plus",
        options=["disconnected", "connected"],
    ),
    EcoFlowSensorDef(
        key="extra_bat1_soc",
        name="Extra Battery 1 Level",
        state_key="bms_kitInfo.watts",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="extra_bat1_soc_precise",
        name="Extra Battery 1 Level (Precise)",
        state_key="bms_kitInfo.watts",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="extra_bat1_power",
        name="Extra Battery 1 Power",
        state_key="bms_kitInfo.watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    # ========================================================================
    # Extra Battery 2 (bms_kitInfo.watts[1])
    # Note: These sensors use kit_index/kit_field for array element access.
    # ========================================================================
    EcoFlowSensorDef(
        key="extra_bat2_connected",
        name="Extra Battery 2 Connected",
        state_key="bms_kitInfo.watts",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-plus",
        options=["disconnected", "connected"],
    ),
    EcoFlowSensorDef(
        key="extra_bat2_soc",
        name="Extra Battery 2 Level",
        state_key="bms_kitInfo.watts",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="extra_bat2_soc_precise",
        name="Extra Battery 2 Level (Precise)",
        state_key="bms_kitInfo.watts",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="extra_bat2_power",
        name="Extra Battery 2 Power",
        state_key="bms_kitInfo.watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    # ========================================================================
    # EMS - Energy Management System (Charge Settings)
    # ========================================================================
    EcoFlowSensorDef(
        key="ems_max_charge_soc",
        name="Max Charge Level",
        state_key="bms_emsStatus.maxChargeSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging-100",
    ),
    EcoFlowSensorDef(
        key="ems_min_dsg_soc",
        name="Min Discharge Level",
        state_key="bms_emsStatus.minDsgSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-10",
    ),
    EcoFlowSensorDef(
        key="ems_lcd_soc",
        name="LCD Display SOC",
        state_key="bms_emsStatus.f32LcdShowSoc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="ems_chg_remain_time",
        name="Charge Remaining Time",
        state_key="bms_emsStatus.chgRemainTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="ems_dsg_remain_time",
        name="Discharge Remaining Time",
        state_key="bms_emsStatus.dsgRemainTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-arrow-down",
    ),
    EcoFlowSensorDef(
        key="ems_generator_on_soc",
        name="Generator Auto Start SOC",
        state_key="bms_emsStatus.openOilSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:engine",
    ),
    EcoFlowSensorDef(
        key="ems_generator_off_soc",
        name="Generator Auto Stop SOC",
        state_key="bms_emsStatus.closeOilSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:engine-off",
    ),
    # ========================================================================
    # EMS - Extended Status
    # ========================================================================
    EcoFlowSensorDef(
        key="ems_chg_amp",
        name="EMS Charge Current",
        state_key="bms_emsStatus.chgAmp",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    EcoFlowSensorDef(
        key="ems_chg_vol",
        name="EMS Charge Voltage",
        state_key="bms_emsStatus.chgVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="ems_chg_state",
        name="EMS Charge State",
        state_key="bms_emsStatus.chgState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-charging",
        options=["not_charging", "charging"],
    ),
    EcoFlowSensorDef(
        key="ems_chg_cmd",
        name="EMS Charge Command",
        state_key="bms_emsStatus.chgCmd",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-charging",
        options=["disabled", "enabled"],
    ),
    EcoFlowSensorDef(
        key="ems_dsg_cmd",
        name="EMS Discharge Command",
        state_key="bms_emsStatus.dsgCmd",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-arrow-down",
        options=["disabled", "enabled"],
    ),
    EcoFlowSensorDef(
        key="ems_fan_level",
        name="EMS Fan Level",
        state_key="bms_emsStatus.fanLevel",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:fan",
        options=["off", "level_1", "level_2", "level_3"],
    ),
    EcoFlowSensorDef(
        key="ems_open_ups_flag",
        name="UPS Mode Enabled",
        state_key="bms_emsStatus.openUpsFlag",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:power-plug-battery",
        options=["disabled", "enabled"],
    ),
    EcoFlowSensorDef(
        key="ems_war_state",
        name="EMS Warning State",
        state_key="bms_emsStatus.bmsWarState",
        icon="mdi:alert",
    ),
    EcoFlowSensorDef(
        key="ems_is_normal_flag",
        name="EMS Normal Status",
        state_key="bms_emsStatus.emsIsNormalFlag",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:check-circle",
        options=["sleep", "normal"],
    ),
    EcoFlowSensorDef(
        key="ems_para_vol_min",
        name="EMS Min Parallel Voltage",
        state_key="bms_emsStatus.paraVolMin",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="ems_para_vol_max",
        name="EMS Max Parallel Voltage",
        state_key="bms_emsStatus.paraVolMax",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="ems_chg_line_plug",
        name="Charge Line Plugged",
        state_key="bms_emsStatus.chgLinePlug",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:power-plug",
        options=["unplugged", "plugged"],
    ),
    # ========================================================================
    # PD - Power Distribution (Input/Output)
    # ========================================================================
    EcoFlowSensorDef(
        key="pd_soc",
        name="Display SOC",
        state_key="pd.soc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="pd_watts_in_sum",
        name="Total Input Power",
        state_key="pd.wattsInSum",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:transmission-tower-import",
    ),
    EcoFlowSensorDef(
        key="pd_watts_out_sum",
        name="Total Output Power",
        state_key="pd.wattsOutSum",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:transmission-tower-export",
    ),
    EcoFlowSensorDef(
        key="pd_remain_time",
        name="Remaining Time",
        state_key="pd.remainTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="pd_usb1_watts",
        name="USB-A 1 Power",
        state_key="pd.usb1Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb",
    ),
    EcoFlowSensorDef(
        key="pd_usb2_watts",
        name="USB-A 2 Power",
        state_key="pd.usb2Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb",
    ),
    EcoFlowSensorDef(
        key="pd_qc_usb1_watts",
        name="QC USB 1 Power",
        state_key="pd.qcUsb1Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb",
    ),
    EcoFlowSensorDef(
        key="pd_qc_usb2_watts",
        name="QC USB 2 Power",
        state_key="pd.qcUsb2Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb",
    ),
    EcoFlowSensorDef(
        key="pd_typec1_watts",
        name="USB-C 1 Power",
        state_key="pd.typec1Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-c-port",
    ),
    EcoFlowSensorDef(
        key="pd_typec2_watts",
        name="USB-C 2 Power",
        state_key="pd.typec2Watts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-c-port",
    ),
    EcoFlowSensorDef(
        key="pd_typec1_temp",
        name="USB-C 1 Temperature",
        state_key="pd.typec1Temp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="pd_typec2_temp",
        name="USB-C 2 Temperature",
        state_key="pd.typec2Temp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="pd_car_watts",
        name="Car Output Power",
        state_key="pd.carWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car",
    ),
    EcoFlowSensorDef(
        key="pd_car_temp",
        name="Car Output Temperature",
        state_key="pd.carTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="pd_standby_min",
        name="Device Standby Time",
        state_key="pd.standbyMin",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer-sleep",
    ),
    EcoFlowSensorDef(
        key="pd_lcd_off_sec",
        name="Screen Timeout",
        state_key="pd.lcdOffSec",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:monitor-off",
    ),
    EcoFlowSensorDef(
        key="pd_bright_level",
        name="Screen Brightness",
        state_key="pd.brightLevel",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:brightness-6",
    ),
    EcoFlowSensorDef(
        key="pd_err_code",
        name="PD Error Code",
        state_key="pd.errCode",
        icon="mdi:alert-circle",
    ),
    EcoFlowSensorDef(
        key="pd_wifi_rssi",
        name="WiFi Signal Strength",
        state_key="pd.wifiRssi",
        unit="dBm",
        device_class=SensorDeviceClass.SIGNAL_STRENGTH,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:wifi",
    ),
    # ========================================================================
    # External Ports Status
    # ========================================================================
    EcoFlowSensorDef(
        key="pd_ext_rj45_port",
        name="RJ45 Port Status",
        state_key="pd.extRj45Port",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:ethernet",
        options=["null", "rc_ble_ctl"],
    ),
    EcoFlowSensorDef(
        key="pd_ext_3p8_port",
        name="Right Port Status (3+8)",
        state_key="pd.ext3p8Port",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["null", "cc", "pr", "sp_bc"],
    ),
    EcoFlowSensorDef(
        key="pd_ext_4p8_port",
        name="Left Port Status (4+8)",
        state_key="pd.ext4p8Port",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["null", "extra_battery", "smart_generator"],
    ),
    # ========================================================================
    # PD - Extended Power & Energy
    # ========================================================================
    EcoFlowSensorDef(
        key="pd_chg_power_ac",
        name="Cumulative AC Charge",
        state_key="pd.chgPowerAC",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:lightning-bolt",
    ),
    EcoFlowSensorDef(
        key="pd_chg_power_dc",
        name="Cumulative DC Charge",
        state_key="pd.chgPowerDC",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:current-dc",
    ),
    EcoFlowSensorDef(
        key="pd_chg_sun_power",
        name="Cumulative Solar Charge",
        state_key="pd.chgSunPower",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="pd_dsg_power_ac",
        name="Cumulative AC Discharge",
        state_key="pd.dsgPowerAC",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:power-socket",
    ),
    EcoFlowSensorDef(
        key="pd_dsg_power_dc",
        name="Cumulative DC Discharge",
        state_key="pd.dsgPowerDC",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:usb",
    ),
    # ========================================================================
    # PD - Extended Status & Control
    # ========================================================================
    EcoFlowSensorDef(
        key="pd_dc_out_state",
        name="DC Output State",
        state_key="pd.dcOutState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:usb",
        options=["off", "on"],
    ),
    EcoFlowSensorDef(
        key="pd_car_state",
        name="Car Output State",
        state_key="pd.carState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:car",
        options=["off", "on"],
    ),
    EcoFlowSensorDef(
        key="pd_ac_enabled",
        name="AC Output Enabled",
        state_key="pd.acEnabled",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:power-socket",
        options=["off", "on"],
    ),
    EcoFlowSensorDef(
        key="pd_chg_dsg_state",
        name="Charge/Discharge State",
        state_key="pd.chgDsgState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-sync",
        options=["idle", "discharging", "charging"],
    ),
    EcoFlowSensorDef(
        key="pd_beep_mode",
        name="Beep Mode",
        state_key="pd.beepMode",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:volume-high",
        options=["normal", "silent"],
    ),
    EcoFlowSensorDef(
        key="pd_charger_type",
        name="Charger Type",
        state_key="pd.chargerType",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:ev-plug-type2",
        options=["none", "ac", "dc_adapter", "solar", "cc", "bc"],
    ),
    EcoFlowSensorDef(
        key="pd_bp_power_soc",
        name="Backup Reserve Level",
        state_key="pd.bpPowerSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-lock",
    ),
    EcoFlowSensorDef(
        key="pd_min_ac_out_soc",
        name="Min AC Output SOC",
        state_key="pd.minAcoutSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-alert",
    ),
    EcoFlowSensorDef(
        key="pd_pv_chg_prio_set",
        name="Solar Charge Priority",
        state_key="pd.pvChgPrioSet",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:solar-power",
        options=["not_prioritized", "prioritized"],
    ),
    # ========================================================================
    # PD - Usage Time Statistics
    # ========================================================================
    EcoFlowSensorDef(
        key="pd_inv_used_time",
        name="Inverter Used Time",
        state_key="pd.invUsedTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="pd_mppt_used_time",
        name="MPPT Used Time",
        state_key="pd.mpptUsedTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="pd_car_used_time",
        name="Car Output Used Time",
        state_key="pd.carUsedTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="pd_usb_used_time",
        name="USB Used Time",
        state_key="pd.usbUsedTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="pd_typec_used_time",
        name="USB-C Used Time",
        state_key="pd.typecUsedTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="pd_dc_in_used_time",
        name="DC Input Used Time",
        state_key="pd.dcInUsedTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:timer",
    ),
    # ========================================================================
    # INV - Inverter
    # ========================================================================
    EcoFlowSensorDef(
        key="inv_input_watts",
        name="AC Charging Power",
        state_key="inv.inputWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:power-plug",
    ),
    EcoFlowSensorDef(
        key="inv_output_watts",
        name="AC Discharging Power",
        state_key="inv.outputWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:power-socket",
    ),
    EcoFlowSensorDef(
        key="inv_out_vol",
        name="AC Output Voltage",
        state_key="inv.invOutVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_out_amp",
        name="AC Output Current",
        state_key="inv.invOutAmp",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_out_freq",
        name="AC Output Frequency",
        state_key="inv.invOutFreq",
        unit=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:sine-wave",
    ),
    EcoFlowSensorDef(
        key="inv_ac_in_vol",
        name="AC Input Voltage",
        state_key="inv.acInVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_ac_in_amp",
        name="AC Input Current",
        state_key="inv.acInAmp",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_ac_in_freq",
        name="AC Input Frequency",
        state_key="inv.acInFreq",
        unit=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:sine-wave",
    ),
    EcoFlowSensorDef(
        key="inv_out_temp",
        name="Inverter Temperature",
        state_key="inv.outTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_standby_mins",
        name="AC Standby Time",
        state_key="inv.standbyMins",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="inv_cfg_ac_out_freq",
        name="AC Output Frequency Setting",
        state_key="inv.cfgAcOutFreq",
        icon="mdi:sine-wave",
    ),
    EcoFlowSensorDef(
        key="inv_err_code",
        name="Inverter Error Code",
        state_key="inv.errCode",
        icon="mdi:alert-circle",
    ),
    # ========================================================================
    # INV - Extended
    # ========================================================================
    EcoFlowSensorDef(
        key="inv_dc_in_vol",
        name="DC Input Voltage",
        state_key="inv.dcInVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_dc_in_amp",
        name="DC Input Current",
        state_key="inv.dcInAmp",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_dc_in_temp",
        name="DC Input Temperature",
        state_key="inv.dcInTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_fast_chg_watts",
        name="Fast Charge Power",
        state_key="inv.FastChgWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    EcoFlowSensorDef(
        key="inv_slow_chg_watts",
        name="Slow Charge Power",
        state_key="inv.SlowChgWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash-outline",
    ),
    EcoFlowSensorDef(
        key="inv_charger_type",
        name="Inverter Charger Type",
        state_key="inv.chargerType",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:ev-plug-type2",
        options=["none", "ac", "dc_adapter", "solar", "cc", "bc"],
    ),
    EcoFlowSensorDef(
        key="inv_discharge_type",
        name="Inverter Discharge Type",
        state_key="inv.dischargeType",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:power-socket",
        options=["none", "ac", "pr", "bc"],
    ),
    EcoFlowSensorDef(
        key="inv_fan_state",
        name="Inverter Fan State",
        state_key="inv.fanState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:fan",
        options=["off", "level_1", "level_2", "level_3"],
    ),
    EcoFlowSensorDef(
        key="inv_cfg_ac_enabled",
        name="AC Output Enabled Config",
        state_key="inv.cfgAcEnabled",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:power-socket",
        options=["off", "on"],
    ),
    EcoFlowSensorDef(
        key="inv_cfg_ac_xboost",
        name="X-Boost Enabled",
        state_key="inv.cfgAcXboost",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:rocket-launch",
        options=["off", "on"],
    ),
    EcoFlowSensorDef(
        key="inv_cfg_ac_out_vol",
        name="AC Output Voltage Config",
        state_key="inv.cfgAcOutVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="inv_cfg_ac_work_mode",
        name="AC Work Mode",
        state_key="inv.cfgAcWorkMode",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:cog",
        options=["full_power", "mute"],
    ),
    EcoFlowSensorDef(
        key="inv_chg_pause_flag",
        name="Inverter Charge Pause",
        state_key="inv.chgPauseFlag",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:pause-circle",
        options=["normal", "paused"],
    ),
    EcoFlowSensorDef(
        key="inv_ac_dip_switch",
        name="AC DIP Switch",
        state_key="inv.acDipSwitch",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:toggle-switch",
        options=["unknown", "fast_charging", "slow_charging"],
    ),
    # ========================================================================
    # MPPT - Solar Charger
    # ========================================================================
    EcoFlowSensorDef(
        key="mppt_in_watts",
        name="Solar Input Power",
        state_key="mppt.inWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="mppt_in_vol",
        name="Solar Input Voltage",
        state_key="mppt.inVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="mppt_in_amp",
        name="Solar Input Current",
        state_key="mppt.inAmp",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="mppt_out_watts",
        name="MPPT Output Power",
        state_key="mppt.outWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    EcoFlowSensorDef(
        key="mppt_out_vol",
        name="MPPT Output Voltage",
        state_key="mppt.outVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="mppt_out_amp",
        name="MPPT Output Current",
        state_key="mppt.outAmp",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="mppt_temp",
        name="MPPT Temperature",
        state_key="mppt.mpptTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="mppt_dc12v_watts",
        name="DC 12V Output Power",
        state_key="mppt.dcdc12vWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-battery",
    ),
    EcoFlowSensorDef(
        key="mppt_dc12v_vol",
        name="DC 12V Output Voltage",
        state_key="mppt.dcdc12vVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-battery",
    ),
    EcoFlowSensorDef(
        key="mppt_dc12v_amp",
        name="DC 12V Output Current",
        state_key="mppt.dcdc12vAmp",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-battery",
    ),
    EcoFlowSensorDef(
        key="mppt_car_out_watts",
        name="Car Charger Output Power",
        state_key="mppt.carOutWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car",
    ),
    EcoFlowSensorDef(
        key="mppt_car_out_vol",
        name="Car Charger Output Voltage",
        state_key="mppt.carOutVol",
        unit=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car",
    ),
    EcoFlowSensorDef(
        key="mppt_car_out_amp",
        name="Car Charger Output Current",
        state_key="mppt.carOutAmp",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car",
    ),
    EcoFlowSensorDef(
        key="mppt_car_temp",
        name="Car Charger Temperature",
        state_key="mppt.carTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="mppt_cfg_chg_watts",
        name="AC Charging Power Limit",
        state_key="mppt.cfgChgWatts",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:lightning-bolt",
    ),
    EcoFlowSensorDef(
        key="mppt_dc_chg_current",
        name="DC Charging Current Limit",
        state_key="mppt.dcChgCurrent",
        unit=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    EcoFlowSensorDef(
        key="mppt_ac_standby_mins",
        name="AC Standby Time Setting",
        state_key="mppt.acStandbyMins",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="mppt_car_standby_min",
        name="Car Standby Time Setting",
        state_key="mppt.carStandbyMin",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="mppt_fault_code",
        name="MPPT Fault Code",
        state_key="mppt.faultCode",
        icon="mdi:alert-circle",
    ),
    # ========================================================================
    # MPPT - Extended
    # ========================================================================
    EcoFlowSensorDef(
        key="mppt_chg_type",
        name="MPPT Charge Type",
        state_key="mppt.chgType",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:flash",
        options=["null", "adapter", "mppt_solar", "ac", "gas", "wind"],
    ),
    EcoFlowSensorDef(
        key="mppt_chg_state",
        name="MPPT Charge State",
        state_key="mppt.chgState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-charging",
        options=["off", "charging", "standby"],
    ),
    EcoFlowSensorDef(
        key="mppt_chg_pause_flag",
        name="MPPT Charge Pause",
        state_key="mppt.chgPauseFlag",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:pause-circle",
        options=["normal", "paused"],
    ),
    EcoFlowSensorDef(
        key="mppt_cfg_chg_type",
        name="MPPT Charge Type Config",
        state_key="mppt.cfgChgType",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:cog",
        options=["auto", "mppt", "adapter"],
    ),
    EcoFlowSensorDef(
        key="mppt_car_state",
        name="Car Charger State",
        state_key="mppt.carState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:car",
        options=["off", "on"],
    ),
    EcoFlowSensorDef(
        key="mppt_discharge_type",
        name="MPPT Discharge Type",
        state_key="mppt.dischargeType",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:power-socket",
        options=["none", "ac", "pr", "bc"],
    ),
    EcoFlowSensorDef(
        key="mppt_dc24v_state",
        name="DC 24V State",
        state_key="mppt.dc24vState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:flash",
        options=["off", "on"],
    ),
    EcoFlowSensorDef(
        key="mppt_dc24v_temp",
        name="DC 24V Temperature",
        state_key="mppt.dc24vTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="mppt_beep_state",
        name="MPPT Beep State",
        state_key="mppt.beepState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:volume-high",
        options=["default", "silent"],
    ),
    EcoFlowSensorDef(
        key="mppt_cfg_ac_enabled",
        name="MPPT AC Enabled Config",
        state_key="mppt.cfgAcEnabled",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:power-socket",
        options=["off", "on"],
    ),
    EcoFlowSensorDef(
        key="mppt_cfg_ac_xboost",
        name="MPPT X-Boost Config",
        state_key="mppt.cfgAcXboost",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:rocket-launch",
        options=["off", "on"],
    ),
    EcoFlowSensorDef(
        key="mppt_cfg_ac_out_vol",
        name="MPPT AC Output Voltage Config",
        state_key="mppt.cfgAcOutVol",
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="mppt_cfg_ac_out_freq",
        name="MPPT AC Output Frequency Config",
        state_key="mppt.cfgAcOutFreq",
        unit=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:sine-wave",
    ),
    EcoFlowSensorDef(
        key="mppt_scr_standby_min",
        name="Screen Standby Time",
        state_key="mppt.scrStandbyMin",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="mppt_pow_standby_min",
        name="Power Standby Time",
        state_key="mppt.powStandbyMin",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="mppt_x60_chg_type",
        name="XT60 Charge Type",
        state_key="mppt.x60ChgType",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:power-plug",
        options=["not_detected", "mppt", "adapter"],
    ),
]
