"""Delta 2 switch definitions."""

from __future__ import annotations

from homeassistant.components.switch import SwitchDeviceClass

from ..base import EcoFlowSwitchDef

SWITCHES = [
    EcoFlowSwitchDef(
        key="ac_output",
        name="AC Output",
        state_key="mppt.cfgAcEnabled",
        param_key="enabled",
        command_params={"module_type": 5, "operate_type": "acOutCfg"},
        value_on=1,
        value_off=0,
        icon_on="mdi:power-socket",
        icon_off="mdi:power-socket-off",
        device_class=SwitchDeviceClass.OUTLET,
        state_interpreter="int01",
    ),
    EcoFlowSwitchDef(
        key="x_boost",
        name="X-Boost",
        state_key="mppt.cfgAcXboost",
        param_key="xboost",
        command_params={"module_type": 5, "operate_type": "acOutCfg"},
        value_on=1,
        value_off=0,
        icon_on="mdi:lightning-bolt",
        icon_off="mdi:lightning-bolt-outline",
        device_class=SwitchDeviceClass.SWITCH,
        state_interpreter="int01",
    ),
    EcoFlowSwitchDef(
        key="dc_usb_output",
        name="DC/USB Output",
        state_key="pd.dcOutState",
        param_key="enabled",
        command_params={"module_type": 1, "operate_type": "dcOutCfg"},
        value_on=1,
        value_off=0,
        icon_on="mdi:usb",
        icon_off="mdi:usb-off",
        device_class=SwitchDeviceClass.OUTLET,
        state_interpreter="int01",
    ),
    EcoFlowSwitchDef(
        key="car_charger",
        name="Car Charger",
        state_key="mppt.carState",
        param_key="enabled",
        command_params={"module_type": 5, "operate_type": "mpptCar"},
        value_on=1,
        value_off=0,
        icon_on="mdi:car",
        icon_off="mdi:car-off",
        device_class=SwitchDeviceClass.SWITCH,
        state_interpreter="int01",
    ),
    EcoFlowSwitchDef(
        key="beeper",
        name="Beeper",
        state_key="mppt.beepState",
        param_key="enabled",
        command_params={"module_type": 5, "operate_type": "quietMode"},
        value_on=1,
        value_off=0,
        icon_on="mdi:volume-high",
        icon_off="mdi:volume-off",
        device_class=SwitchDeviceClass.SWITCH,
        inverted=True,
        state_interpreter="int01",
    ),
    EcoFlowSwitchDef(
        key="ac_always_on",
        name="AC Always On",
        state_key="pd.acAutoOutConfig",
        param_key="acAutoOutConfig",
        command_params={"module_type": 1, "operate_type": "acAutoOutConfig"},
        value_on=1,
        value_off=0,
        icon_on="mdi:power-plug",
        icon_off="mdi:power-plug-off",
        device_class=SwitchDeviceClass.SWITCH,
        state_interpreter="int01",
    ),
]
