"""Delta Pro 3 number definitions."""

from __future__ import annotations

from homeassistant.components.number import NumberMode
from homeassistant.const import PERCENTAGE, UnitOfElectricCurrent, UnitOfPower, UnitOfTime

from ..base import EcoFlowNumberDef

NUMBERS = [
    EcoFlowNumberDef(
        key="max_charge_level",
        name="Max Charge Level",
        state_key="cmsMaxChgSoc",
        param_key="cfgMaxChgSoc",
        min_value=0,
        max_value=100,
        step=1,
        unit=PERCENTAGE,
        icon="mdi:battery-charging-100",
    ),
    EcoFlowNumberDef(
        key="min_discharge_level",
        name="Min Discharge Level",
        state_key="cmsMinDsgSoc",
        param_key="cfgMinDsgSoc",
        min_value=0,
        max_value=100,
        step=1,
        unit=PERCENTAGE,
        icon="mdi:battery-10",
    ),
    EcoFlowNumberDef(
        key="ac_charge_power",
        name="AC Charge Power",
        state_key="plugInInfoAcInChgPowMax",
        param_key="cfgPlugInInfoAcInChgPowMax",
        min_value=400,
        max_value=2900,
        step=100,
        unit=UnitOfPower.WATT,
        icon="mdi:lightning-bolt",
    ),
    EcoFlowNumberDef(
        key="lcd_brightness",
        name="LCD Brightness",
        state_key="lcdLight",
        param_key="cfgLcdLight",
        min_value=0,
        max_value=100,
        step=10,
        unit=PERCENTAGE,
        icon="mdi:brightness-6",
    ),
    EcoFlowNumberDef(
        key="screen_off_time",
        name="Screen Off Time",
        state_key="screenOffTime",
        param_key="cfgScreenOffTime",
        min_value=0,
        max_value=3600,
        step=30,
        unit=UnitOfTime.SECONDS,
        icon="mdi:monitor-off",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="generator_start_soc",
        name="Generator Start SOC",
        state_key="cmsOilOnSoc",
        param_key="cfgCmsOilOnSoc",
        min_value=0,
        max_value=100,
        step=5,
        unit=PERCENTAGE,
        icon="mdi:engine",
    ),
    EcoFlowNumberDef(
        key="generator_stop_soc",
        name="Generator Stop SOC",
        state_key="cmsOilOffSoc",
        param_key="cfgCmsOilOffSoc",
        min_value=0,
        max_value=100,
        step=5,
        unit=PERCENTAGE,
        icon="mdi:engine-off",
    ),
    EcoFlowNumberDef(
        key="pv_lv_max_current",
        name="Solar LV Max Current",
        state_key="plugInInfoPvLDcAmpMax",
        param_key="cfgPlugInInfoPvLDcAmpMax",
        min_value=0,
        max_value=8,
        step=1,
        unit=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="pv_hv_max_current",
        name="Solar HV Max Current",
        state_key="plugInInfoPvHDcAmpMax",
        param_key="cfgPlugInInfoPvHDcAmpMax",
        min_value=0,
        max_value=20,
        step=1,
        unit=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="power_inout_max_charge",
        name="Power In/Out Max Charge",
        state_key="plugInInfo5p8ChgPowMax",
        param_key="cfgPlugInInfo5p8ChgPowMax",
        min_value=0,
        max_value=4000,
        step=100,
        unit=UnitOfPower.WATT,
        icon="mdi:battery-charging",
    ),
    EcoFlowNumberDef(
        key="device_standby_time",
        name="Device Standby Time",
        state_key="devStandbyTime",
        param_key="cfgDevStandbyTime",
        min_value=0,
        max_value=1440,
        step=30,
        unit=UnitOfTime.MINUTES,
        icon="mdi:timer",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="ble_standby_time",
        name="Bluetooth Standby Time",
        state_key="bleStandbyTime",
        param_key="cfgBleStandbyTime",
        min_value=0,
        max_value=3600,
        step=60,
        unit=UnitOfTime.SECONDS,
        icon="mdi:bluetooth",
        mode=NumberMode.BOX,
    ),
    EcoFlowNumberDef(
        key="backup_reserve_level",
        name="Backup Reserve Level",
        state_key="backupReverseSoc",
        param_key="cfgEnergyBackup",
        min_value=0,
        max_value=100,
        step=1,
        unit=PERCENTAGE,
        icon="mdi:battery-lock",
        nested_params={"energyBackupStartSoc": None, "energyBackupEn": True},
    ),
    EcoFlowNumberDef(
        key="generator_pv_hybrid_max_soc",
        name="Generator PV Hybrid Max SOC",
        state_key="generatorPvHybridModeSocMax",
        param_key="cfgGeneratorPvHybridModeSocMax",
        min_value=0,
        max_value=100,
        step=1,
        unit=PERCENTAGE,
        icon="mdi:battery-charging-100",
    ),
    EcoFlowNumberDef(
        key="generator_care_start_time",
        name="Generator Care Mode Start Time",
        state_key="generatorCareModeStartTime",
        param_key="cfgGeneratorCareModeStartTime",
        min_value=0,
        max_value=1440,
        step=1,
        unit=UnitOfTime.MINUTES,
        icon="mdi:clock-start",
        mode=NumberMode.BOX,
    ),
]
