"""Delta Pro 3 sensor definitions."""

from __future__ import annotations

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfTime,
)

from ..base import EcoFlowSensorDef

SENSORS = [
    # ========================================================================
    # BATTERY - Main Battery (BMS)
    # ========================================================================
    EcoFlowSensorDef(
        key="bms_batt_soc",
        name="Battery Level",
        state_key="bmsBattSoc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_batt_soh",
        name="Battery Health",
        state_key="bmsBattSoh",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart",
    ),
    EcoFlowSensorDef(
        key="bms_design_cap",
        name="Battery Design Capacity",
        state_key="bmsDesignCap",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery",
    ),
    EcoFlowSensorDef(
        key="bms_chg_rem_time",
        name="Charge Remaining Time",
        state_key="bmsChgRemTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="bms_dsg_rem_time",
        name="Discharge Remaining Time",
        state_key="bmsDsgRemTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-arrow-down",
    ),
    EcoFlowSensorDef(
        key="bms_chg_dsg_state",
        name="Charge/Discharge State",
        state_key="bmsChgDsgState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-sync",
        options=["idle", "charging", "discharging"],
    ),
    EcoFlowSensorDef(
        key="bms_err_code",
        name="BMS Error Code",
        state_key="bmsErrCode",
        icon="mdi:alert-circle",
    ),
    EcoFlowSensorDef(
        key="bms_cycles",
        name="Battery Cycles",
        state_key="cycles",
        unit="cycles",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:sync",
    ),
    # ========================================================================
    # BATTERY - CMS (Combined Management System)
    # ========================================================================
    EcoFlowSensorDef(
        key="cms_batt_soc",
        name="System Battery Level",
        state_key="cmsBattSoc",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="cms_batt_soh",
        name="System Battery Health",
        state_key="cmsBattSoh",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart",
    ),
    EcoFlowSensorDef(
        key="cms_batt_full_energy",
        name="System Full Energy",
        state_key="cmsBattFullEnergy",
        unit=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery",
    ),
    EcoFlowSensorDef(
        key="cms_batt_pow_in_max",
        name="Max Input Power",
        state_key="cmsBattPowInMax",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging-high",
    ),
    EcoFlowSensorDef(
        key="cms_batt_pow_out_max",
        name="Max Output Power",
        state_key="cmsBattPowOutMax",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-arrow-down",
    ),
    EcoFlowSensorDef(
        key="cms_bms_run_state",
        name="BMS Run State",
        state_key="cmsBmsRunState",
        icon="mdi:state-machine",
    ),
    EcoFlowSensorDef(
        key="cms_chg_dsg_state",
        name="System Charge/Discharge State",
        state_key="cmsChgDsgState",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:battery-sync",
        options=["idle", "charging", "discharging"],
    ),
    EcoFlowSensorDef(
        key="cms_chg_rem_time",
        name="System Charge Remaining Time",
        state_key="cmsChgRemTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="cms_dsg_rem_time",
        name="System Discharge Remaining Time",
        state_key="cmsDsgRemTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-arrow-down",
    ),
    EcoFlowSensorDef(
        key="cms_max_chg_soc",
        name="Max Charge Level Setting",
        state_key="cmsMaxChgSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging-100",
    ),
    EcoFlowSensorDef(
        key="cms_min_dsg_soc",
        name="Min Discharge Level Setting",
        state_key="cmsMinDsgSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-10",
    ),
    # ========================================================================
    # TEMPERATURE
    # ========================================================================
    EcoFlowSensorDef(
        key="bms_max_cell_temp",
        name="Max Cell Temperature",
        state_key="bmsMaxCellTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_min_cell_temp",
        name="Min Cell Temperature",
        state_key="bmsMinCellTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    EcoFlowSensorDef(
        key="bms_max_mos_temp",
        name="Max MOS Temperature",
        state_key="bmsMaxMosTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-high",
    ),
    EcoFlowSensorDef(
        key="bms_min_mos_temp",
        name="Min MOS Temperature",
        state_key="bmsMinMosTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-low",
    ),
    # BMS Detailed Temperature Sensors (from BMS heartbeat - without prefix)
    EcoFlowSensorDef(
        key="max_cell_temp",
        name="BMS Max Cell Temp",
        state_key="maxCellTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-high",
    ),
    EcoFlowSensorDef(
        key="min_cell_temp",
        name="BMS Min Cell Temp",
        state_key="minCellTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-low",
    ),
    EcoFlowSensorDef(
        key="max_mos_temp",
        name="BMS Max MOS Temp",
        state_key="maxMosTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-high",
    ),
    EcoFlowSensorDef(
        key="min_mos_temp",
        name="BMS Min MOS Temp",
        state_key="minMosTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-low",
    ),
    EcoFlowSensorDef(
        key="max_env_temp",
        name="Max Environment Temp",
        state_key="maxEnvTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-high",
    ),
    EcoFlowSensorDef(
        key="min_env_temp",
        name="Min Environment Temp",
        state_key="minEnvTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-low",
    ),
    EcoFlowSensorDef(
        key="max_cur_sensor_temp",
        name="Max Current Sensor Temp",
        state_key="maxCurSensorTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-high",
    ),
    EcoFlowSensorDef(
        key="min_cur_sensor_temp",
        name="Min Current Sensor Temp",
        state_key="minCurSensorTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-low",
    ),
    EcoFlowSensorDef(
        key="bms_temp",
        name="BMS Temperature",
        state_key="temp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer",
    ),
    # PCS/LLC/Inverter Temperature Sensors
    EcoFlowSensorDef(
        key="inv_ntc_temp_2",
        name="Inverter NTC Temp 2",
        state_key="invNtcTemp2",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer",
    ),
    EcoFlowSensorDef(
        key="inv_ntc_temp_3",
        name="Inverter NTC Temp 3",
        state_key="invNtcTemp3",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer",
    ),
    EcoFlowSensorDef(
        key="ads_ntc_temp",
        name="ADS NTC Temperature",
        state_key="adsNtcTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer",
    ),
    EcoFlowSensorDef(
        key="llc_ntc_temp",
        name="LLC NTC Temperature",
        state_key="llcNtcTemp",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer",
    ),
    EcoFlowSensorDef(
        key="temp_pv_h",
        name="Solar HV Temperature",
        state_key="tempPvH",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="temp_pv_l",
        name="Solar LV Temperature",
        state_key="tempPvL",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="temp_pcs_ac",
        name="PCS AC Temperature",
        state_key="tempPcsAc",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer",
    ),
    EcoFlowSensorDef(
        key="temp_pcs_dc",
        name="PCS DC Temperature",
        state_key="tempPcsDc",
        unit=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer",
    ),
    # ========================================================================
    # POWER - Input
    # ========================================================================
    EcoFlowSensorDef(
        key="pow_in_sum_w",
        name="Total Input Power",
        state_key="powInSumW",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:transmission-tower-import",
    ),
    EcoFlowSensorDef(
        key="pow_get_ac_in",
        name="AC Input Power",
        state_key="powGetAcIn",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:power-plug",
    ),
    EcoFlowSensorDef(
        key="pow_get_pv_h",
        name="Solar HV Input Power",
        state_key="powGetPvH",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="pow_get_pv_l",
        name="Solar LV Input Power",
        state_key="powGetPvL",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
    ),
    EcoFlowSensorDef(
        key="pow_get_5p8",
        name="5.8V Input Power",
        state_key="powGet5p8",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="pow_get_4p81",
        name="4.8V Port 1 Power",
        state_key="powGet4p81",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    EcoFlowSensorDef(
        key="pow_get_4p82",
        name="4.8V Port 2 Power",
        state_key="powGet4p82",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging",
    ),
    # ========================================================================
    # POWER - Output
    # ========================================================================
    EcoFlowSensorDef(
        key="pow_out_sum_w",
        name="Total Output Power",
        state_key="powOutSumW",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:transmission-tower-export",
    ),
    EcoFlowSensorDef(
        key="pow_get_ac_hv_out",
        name="AC HV Output Power",
        state_key="powGetAcHvOut",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:power-socket",
    ),
    EcoFlowSensorDef(
        key="pow_get_ac_lv_out",
        name="AC LV Output Power",
        state_key="powGetAcLvOut",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:power-socket",
    ),
    EcoFlowSensorDef(
        key="pow_get_ac_lv_tt30_out",
        name="AC LV TT30 Output Power",
        state_key="powGetAcLvTt30Out",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:power-socket",
    ),
    EcoFlowSensorDef(
        key="pow_get_12v",
        name="12V DC Output Power",
        state_key="powGet12v",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    EcoFlowSensorDef(
        key="pow_get_24v",
        name="24V DC Output Power",
        state_key="powGet24v",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    EcoFlowSensorDef(
        key="pow_get_qcusb1",
        name="QC USB 1 Output Power",
        state_key="powGetQcusb1",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb",
    ),
    EcoFlowSensorDef(
        key="pow_get_qcusb2",
        name="QC USB 2 Output Power",
        state_key="powGetQcusb2",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb",
    ),
    EcoFlowSensorDef(
        key="pow_get_typec1",
        name="Type-C 1 Output Power",
        state_key="powGetTypec1",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-c-port",
    ),
    EcoFlowSensorDef(
        key="pow_get_typec2",
        name="Type-C 2 Output Power",
        state_key="powGetTypec2",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-c-port",
    ),
    # ========================================================================
    # AC SYSTEM
    # ========================================================================
    EcoFlowSensorDef(
        key="ac_out_freq",
        name="AC Output Frequency",
        state_key="acOutFreq",
        unit=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:sine-wave",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_ac_in_feq",
        name="AC Input Frequency",
        state_key="plugInInfoAcInFeq",
        unit=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:sine-wave",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_ac_in_chg_pow_max",
        name="AC Input Max Charge Power",
        state_key="plugInInfoAcInChgPowMax",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:lightning-bolt",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_ac_in_chg_hal_pow_max",
        name="AC Input Hardware Max Charge Power",
        state_key="plugInInfoAcInChgHalPowMax",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:lightning-bolt",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_ac_out_dsg_pow_max",
        name="AC Output Max Discharge Power",
        state_key="plugInInfoAcOutDsgPowMax",
        unit=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:lightning-bolt",
    ),
    # ========================================================================
    # SOLAR (PV) SYSTEM
    # ========================================================================
    EcoFlowSensorDef(
        key="plug_in_info_pv_h_chg_amp_max",
        name="Solar HV Max Charge Current",
        state_key="plugInInfoPvHChgAmpMax",
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_pv_h_dc_amp_max",
        name="Solar HV Max DC Current",
        state_key="plugInInfoPvHDcAmpMax",
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_pv_h_chg_vol_max",
        name="Solar HV Max Charge Voltage",
        state_key="plugInInfoPvHChgVolMax",
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_pv_l_chg_amp_max",
        name="Solar LV Max Charge Current",
        state_key="plugInInfoPvLChgAmpMax",
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_pv_l_dc_amp_max",
        name="Solar LV Max DC Current",
        state_key="plugInInfoPvLDcAmpMax",
        unit=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:current-dc",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_pv_l_chg_vol_max",
        name="Solar LV Max Charge Voltage",
        state_key="plugInInfoPvLChgVolMax",
        unit=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
    ),
    # ========================================================================
    # PLUG-IN INFO - Extra Batteries
    # ========================================================================
    EcoFlowSensorDef(
        key="plug_in_info_dcp2_sn",
        name="Extra Battery 2 Serial Number",
        state_key="plugInInfoDcp2Sn",
        icon="mdi:battery-plus",
    ),
    EcoFlowSensorDef(
        key="plug_in_info_dcp_sn",
        name="Extra Battery Serial Number",
        state_key="plugInInfoDcpSn",
        icon="mdi:battery-plus",
    ),
    # Extra Battery 1 (Port 4P81) - decoded from resvInfo
    EcoFlowSensorDef(
        key="extra_battery_1_soc",
        name="Extra Battery 1 SOC",
        state_key="plugInInfo4p81Resv.resvInfo",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        resv_index=0,
        resv_type="float",
    ),
    EcoFlowSensorDef(
        key="extra_battery_1_soh",
        name="Extra Battery 1 SOH",
        state_key="plugInInfo4p81Resv.resvInfo",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart",
        resv_index=1,
        resv_type="float",
    ),
    EcoFlowSensorDef(
        key="extra_battery_1_design_capacity",
        name="Extra Battery 1 Design Capacity",
        state_key="plugInInfo4p81Resv.resvInfo",
        unit="Ah",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-high",
        resv_index=3,
        resv_type="mah_to_ah",
    ),
    EcoFlowSensorDef(
        key="extra_battery_1_full_capacity",
        name="Extra Battery 1 Full Capacity",
        state_key="plugInInfo4p81Resv.resvInfo",
        unit="Ah",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-high",
        resv_index=4,
        resv_type="mah_to_ah",
    ),
    EcoFlowSensorDef(
        key="extra_battery_1_remain_capacity",
        name="Extra Battery 1 Remain Capacity",
        state_key="plugInInfo4p81Resv.resvInfo",
        unit="Ah",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-medium",
        resv_index=5,
        resv_type="mah_to_ah",
    ),
    # Extra Battery 2 (Port 4P82) - decoded from resvInfo
    EcoFlowSensorDef(
        key="extra_battery_2_soc",
        name="Extra Battery 2 SOC",
        state_key="plugInInfo4p82Resv.resvInfo",
        unit=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        resv_index=0,
        resv_type="float",
    ),
    EcoFlowSensorDef(
        key="extra_battery_2_soh",
        name="Extra Battery 2 SOH",
        state_key="plugInInfo4p82Resv.resvInfo",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-heart",
        resv_index=1,
        resv_type="float",
    ),
    EcoFlowSensorDef(
        key="extra_battery_2_design_capacity",
        name="Extra Battery 2 Design Capacity",
        state_key="plugInInfo4p82Resv.resvInfo",
        unit="Ah",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-high",
        resv_index=3,
        resv_type="mah_to_ah",
    ),
    EcoFlowSensorDef(
        key="extra_battery_2_full_capacity",
        name="Extra Battery 2 Full Capacity",
        state_key="plugInInfo4p82Resv.resvInfo",
        unit="Ah",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-high",
        resv_index=4,
        resv_type="mah_to_ah",
    ),
    EcoFlowSensorDef(
        key="extra_battery_2_remain_capacity",
        name="Extra Battery 2 Remain Capacity",
        state_key="plugInInfo4p82Resv.resvInfo",
        unit="Ah",
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-medium",
        resv_index=5,
        resv_type="mah_to_ah",
    ),
    # ========================================================================
    # FLOW INFO - Connection Status
    # ========================================================================
    EcoFlowSensorDef(
        key="flow_info_ac_hv_out",
        name="AC HV Output Flow Status",
        state_key="flowInfoAcHvOut",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_ac_lv_out",
        name="AC LV Output Flow Status",
        state_key="flowInfoAcLvOut",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_ac_in",
        name="AC Input Flow Status",
        state_key="flowInfoAcIn",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_pv_h",
        name="Solar HV Flow Status",
        state_key="flowInfoPvH",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_pv_l",
        name="Solar LV Flow Status",
        state_key="flowInfoPvL",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_12v",
        name="12V DC Flow Status",
        state_key="flowInfo12v",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_24v",
        name="24V DC Flow Status",
        state_key="flowInfo24v",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_qcusb1",
        name="QC USB 1 Flow Status",
        state_key="flowInfoQcusb1",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_qcusb2",
        name="QC USB 2 Flow Status",
        state_key="flowInfoQcusb2",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_typec1",
        name="Type-C 1 Flow Status",
        state_key="flowInfoTypec1",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    EcoFlowSensorDef(
        key="flow_info_typec2",
        name="Type-C 2 Flow Status",
        state_key="flowInfoTypec2",
        device_class=SensorDeviceClass.ENUM,
        icon="mdi:connection",
        options=["disconnected", "connected", "active"],
    ),
    # ========================================================================
    # SETTINGS & TIMERS
    # ========================================================================
    EcoFlowSensorDef(
        key="ac_standby_time",
        name="AC Standby Time",
        state_key="acStandbyTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="dc_standby_time",
        name="DC Standby Time",
        state_key="dcStandbyTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="ble_standby_time",
        name="Bluetooth Standby Time",
        state_key="bleStandbyTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="screen_off_time",
        name="Screen Off Time",
        state_key="screenOffTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:monitor-off",
    ),
    EcoFlowSensorDef(
        key="lcd_light",
        name="LCD Brightness",
        state_key="lcdLight",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:brightness-6",
    ),
    EcoFlowSensorDef(
        key="backup_reverse_soc",
        name="Backup Reserve SOC",
        state_key="backupReverseSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-lock",
    ),
    # ========================================================================
    # GENERATOR & ENERGY STRATEGY
    # ========================================================================
    EcoFlowSensorDef(
        key="cms_oil_on_soc",
        name="Generator Start SOC",
        state_key="cmsOilOnSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:engine",
    ),
    EcoFlowSensorDef(
        key="cms_oil_off_soc",
        name="Generator Stop SOC",
        state_key="cmsOilOffSoc",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:engine-off",
    ),
    EcoFlowSensorDef(
        key="generator_care_mode_start_time",
        name="Generator Care Mode Start Time",
        state_key="generatorCareModeStartTime",
        unit=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:clock-start",
    ),
    EcoFlowSensorDef(
        key="generator_pv_hybrid_mode_soc_max",
        name="Generator PV Hybrid Max SOC",
        state_key="generatorPvHybridModeSocMax",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-charging-100",
    ),
    # ========================================================================
    # ERROR CODES & STATUS
    # ========================================================================
    EcoFlowSensorDef(
        key="errcode",
        name="Error Code",
        state_key="errcode",
        icon="mdi:alert-circle",
    ),
    EcoFlowSensorDef(
        key="mppt_err_code",
        name="MPPT Error Code",
        state_key="mpptErrCode",
        icon="mdi:alert-circle",
    ),
    EcoFlowSensorDef(
        key="dev_sleep_state",
        name="Device Sleep State",
        state_key="devSleepState",
        icon="mdi:sleep",
    ),
    EcoFlowSensorDef(
        key="dev_standby_time",
        name="Device Standby Time",
        state_key="devStandbyTime",
        unit=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer",
    ),
    EcoFlowSensorDef(
        key="llc_hv_lv_flag",
        name="LLC HV/LV Flag",
        state_key="llcHvLvFlag",
        icon="mdi:flag",
    ),
    EcoFlowSensorDef(
        key="pcs_fan_level",
        name="PCS Fan Level",
        state_key="pcsFanLevel",
        icon="mdi:fan",
    ),
    EcoFlowSensorDef(
        key="multi_bp_chg_dsg_mode",
        name="Multi Battery Pack Mode",
        state_key="multiBpChgDsgMode",
        icon="mdi:battery-sync",
    ),
    # ========================================================================
    # TIMEZONE & TIME
    # ========================================================================
    EcoFlowSensorDef(
        key="utc_timezone",
        name="UTC Timezone Offset",
        state_key="utcTimezone",
        unit="min",
        icon="mdi:clock-outline",
    ),
    EcoFlowSensorDef(
        key="utc_timezone_id",
        name="Timezone ID",
        state_key="utcTimezoneId",
        icon="mdi:map-clock",
    ),
    EcoFlowSensorDef(
        key="quota_cloud_ts",
        name="Cloud Timestamp",
        state_key="quota_cloud_ts",
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:cloud-clock",
    ),
    EcoFlowSensorDef(
        key="quota_device_ts",
        name="Device Timestamp",
        state_key="quota_device_ts",
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:clock-digital",
    ),
]
